#version: '3.8'  # Opsiyonel; Docker Compose'un yeni versiyonlarında bu satırı çıkarabilirsiniz.

services:
  db:
    build:
      context: .
      dockerfile: docker/mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - ./src:/var/www/html

  web:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php
      - db

volumes:
  db_data: