#version: '3.8'  # Optional

services:
  db:
    build:
      context: .
      dockerfile: docker/mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - ./src:/var/www/html

  web:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web interface
      - "1025:1025" # SMTP Server

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: