CREATE DATABASE IF NOT EXISTS exampledb;
USE exampledb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

GRANT ALL PRIVILEGES ON exampledb.* TO 'exampleuser'@'%' IDENTIFIED BY 'examplepassword';
FLUSH PRIVILEGES;